"""empty message

Revision ID: 4b9ee357cc16
Revises: 
Create Date: 2022-07-13 12:24:56.439477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9ee357cc16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_pairs_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_pair', sa.Integer(), nullable=True),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('k', sa.Float(), nullable=False),
    sa.Column('d', sa.Float(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_pair'], ['coin_pairs.id'], name='fk_coin_pairs_data_coin_pairs_id_coin_pair'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coin_pairs_data')
    op.drop_table('coin_pairs')
    # ### end Alembic commands ###
