"""empty message

Revision ID: 907f1161b6c1
Revises: c672e4abe322
Create Date: 2022-07-13 09:06:10.762016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '907f1161b6c1'
down_revision = 'c672e4abe322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coin_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_pairs_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_pair', sa.Integer(), nullable=True),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('k', sa.Float(), nullable=False),
    sa.Column('d', sa.Float(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_pair'], ['Coin_pairs.id'], name='fk_coin_pairs_data_Coin_pairs_id_coin_pair'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coins_data')
    op.drop_table('coins')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('coins_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coins_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('coins_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('k', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('d', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('open_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('close_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coin'], ['coins.id'], name='fk_coins_data_coins_id_coin'),
    sa.PrimaryKeyConstraint('id', name='coins_data_pkey')
    )
    op.drop_table('coin_pairs_data')
    op.drop_table('Coin_pairs')
    # ### end Alembic commands ###
