"""empty message

Revision ID: c672e4abe322
Revises: c14b324583b5
Create Date: 2022-07-13 08:57:09.585194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c672e4abe322'
down_revision = 'c14b324583b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coins_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('k', sa.Float(), nullable=False),
    sa.Column('d', sa.Float(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin'], ['coins.id'], name='fk_coins_data_coins_id_coin'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins_data')
    op.drop_table('coins')
    # ### end Alembic commands ###
