version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  api:
    build: ./api
    ports:
      - '5002:80'
    environment:
      - API_SECRET_KEY=${API_SECRET_KEY} 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./api/alembic:/api/alembic
    links:
      - 'db'
  bot:
    build: ./bot
    ports:
      - '5003'
    environment:
      - BAPI_KEY=${BAPI_KEY} 
      - BAPI_SECRET=${BAPI_SECRET}
    links:
      - 'api'
volumes:
  db:
    driver: local